batch_size = 1024
max_epochs = 90
lr = 10
label_smoothing = 0.1
arch = "resnet50"
use_amp = true

[preprocess]
preload_local = true
interpolation = "bilinear"
train_crop_size = 176
val_image_size = 256
val_crop_size = 224

[optim]
name = 'sgd-schedule-free'
warmup_epochs = 5
momentum = 0.9
weight_decay = 0.00005
r = 0.75
weight_lr_power = 2.0
num_samples_for_stats = 102400

[lr_scheduler]
name = 'constant'

[reproduce]
seed = 810975

[log]
log_freq = 100
wandb_on = true
wandb_project = "reproduce_resnet"
checkpoint_freq = 45
