batch_size = 1024
max_epochs = 90
lr = 1.0
label_smoothing = 0.1
arch = "resnet18"
use_amp = true

[preprocess]
preload_local = true
interpolation = "bilinear"
train_crop_size = 176
val_image_size = 256
val_crop_size = 224

[optim]
name = 'sgd'
momentum = 0.875
weight_decay = 0.000030517578125

[lr_scheduler]
name = 'cosine'
warmup_epochs = 5
warmup_decay = 0.01

[reproduce]
seed = 810977

[log]
log_freq = 100
wandb_on = false
project = "imagenet-baselines"
neptune_on = true
checkpoint_freq = 45
