batch_size = 1024
max_epochs = 90
lr = 6.0
label_smoothing = 0.0
checkpoint_dir = ""
arch = "resnet50"
use_amp = true

[preprocess]
preload_local = true
interpolation = "bilinear"
train_crop_size = 176
val_image_size = 256
val_crop_size = 224

[optim]
name = 'sgd-schedule-free'
momentum = 0.9
weight_decay = 0.00005
r = 0.75

[lr_scheduler]
name = 'constant'

[reproduce]
seed = 810975

[log]
log_dir = './log'
log_freq = 100
wandb_on = true
wandb_project = "reproduce_resnet"
ckpt_freq = 45
