batch_size = 256
max_epochs = 90
lr = 0.0025
label_smoothing = 0.1
checkpoint_dir = ""
arch = "resnet50"
use_amp = true

[preprocess]
preload_local = true
interpolation = "bilinear"
train_crop_size = 224
val_image_size = 256
val_crop_size = 224

[optim]
name = 'adamw-schedule-free'
weight_decay = 0.0

[lr_scheduler]
name = 'constant'

[reproduce]
seed = 810975

[log]
log_dir = './log'
log_freq = 100
wandb_on = true
wandb_project = "reproduce_resnet"
ckpt_freq = 45
